server:
  port: 8081
spring:
  application:
    name: Consumer-app
  datasource:
    url:  jdbc:postgresql://localhost:5432/consumer
    username: juniper
    password: 112233


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
